name: Leeahd Grid test
favicon: null
layout_spectrum: 0.5126991341821849
typography_spectrum: 0.5316727431491017
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.2024445382412523
  lightness: 0.30429668026044965
  saturation: 0.36170980148017406
  rhythmicContrast: 0.6042654598131776
purpose: []
