name: Leeahd Grid test
favicon: null
layout_spectrum: 1
typography_spectrum: 0.21908
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9deef2'
    - '#ffffff'
    - '#413ec9'
    - '#62b3eb'
    - '#392b2a'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.6042654598131776
purpose: []
